name: Deploy react app to github pages
on:
  push:
    branches:
      - env-qa

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdzenie
        uses: actions/checkout@v4

      - name: Przygotuj Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instaluj zależności Python
        run: pip install pandas openpyxl
        working-directory: backend

      - name: Konwertuj Excel na JSON + Update Time
        run: python convertJson.py
        working-directory: backend

      - name: Przygotuj pliki do wrzucenia
        run: |
          mkdir -p _site
          cp -r pages _site/
          cp -r pages-js _site/
          cp -r styles _site/
          cp -r photos _site/
          cp -r backend _site/
          cp -r modules _site/
          cp index.html _site/
          cp index.js _site/

      - name: Wrzuc artefakty
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Wrzucenie na github pages
        id: deployment
        uses: actions/deploy-pages@v4
